import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
// import BgHeader from '../asset/bgHeader.png'
import LogoFull from '../asset/gameLogoFull.png'

const Jumbotron =()=>{
  return (
    <div className="w-full md:h-[684px] h-[600px] relative -z-10 harfishbg bg-fixed bg-clip-border bg-cover flex flex-col justify-center">
      <div className="relative w-full md:w-[775px] md:h-[349px] place-self-center">
        <Image
        alt='logo harfish'
        src={LogoFull}
        layout='responsive'
        objectFit='cover'
        />
      </div>
      <Link href='/play'>
        <div className='w-48 h-12 bg-orange-500 items text-white place-self-center font-light text-center inline-block align-middle py-3 '>PLAY NOW!</div>
      </Link>
    </div>
  )
}

const PageNavigation = () => {
  return (
    <div className="">
      tes page navigation
    </div>
  )
}
export default function Home() {
  return (
    <div>
      <Head>
        <title>Harfish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
        <Jumbotron />
      </header>

      <main>
        {/* page navigation */}
        <PageNavigation/>
        tes main
      </main>

      <footer className={styles.footer}>
        ini footer
      </footer>
    </div>
  )
}
